<?php

namespace Lukehmu\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends EntityRepository
{
    public function findOneByIdJoinedToCategory($id)
    {
    $query = $this->getEntityManager()
        ->createQuery('
            SELECT p, c FROM LukehmuTestBundle:Notes p
            JOIN p.category c
            WHERE p.id = :id'
        )->setParameter('id', $id);

    try {
            return $query->getSingleResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
    }
}
